### Get all Courses
GET http://localhost:8080/Course


### Create new Course
POST http://localhost:8080/Course
Content-Type: application/json

{
  "name": "Course 3",
  "totalHours": 12
}

### Delete Course by id
DELETE http://localhost:8080/Course/725a01ad-d980-4a5c-85e9-814365a0d89b

### Update Course Data

Put http://localhost:8080/Course
Content-Type: application/json

{
  "id": "725a01ad-d980-4a5c-85e9-814365a0d89b" ,
  "name": "Course 2",
  "totalHours": 35
}


#############################################


### Get all Students
GET http://localhost:8080/Student

### Create new Student
POST http://localhost:8080/Student
Content-Type: application/json

{
  "firstName": "Student",
  "lastName": "3",
  "phoneNumber": "875425833"
}

### Delete Student by id
DELETE http://localhost:8080/Student/b66a0faf-3b4a-4422-b9d6-bf628337295a

### Update Student Data

Put http://localhost:8080/localhost:8080/Student
Content-Type: application/json

{
  "id": "f551423a-def5-42b6-b12c-363c4f55f37b",
  "firstName": "Student",
  "lastName": "1",
  "phoneNumber": "90371223454"
}

##################################

### Enroll & Unenroll student in course

### Enrol
### Unenroll
POST http://localhost:8080/Student/enroll
Content-Type: application/json

{
  "studentId": "1c7cf6ed-9810-4712-8abd-93d9260f3cf9",
  "courseId": "081968ce-dd56-41ff-800e-6844078a65ba",
  "role" : "Enrol"
}
