### Get all Courses
GET http://localhost:8080/Course


### Create new Course
POST http://localhost:8080/Course
Content-Type: application/json

{
  "name": "Course 1",
  "totalHours": 25
}

### Delete Course by id
DELETE http://localhost:8080/Course/8b961aa5-4ed3-446e-bc93-8a1a31eeab28

### Update Course Data

Put http://localhost:8080/Course
Content-Type: application/json

{
  "id": "9b60fc69-95e7-4060-aec7-b9ba566e9766" ,
  "name": "Course 2",
  "totalHours": 35
}


#############################################


### Get all Students
GET http://localhost:8080/Student

### Create new Student
POST http://localhost:8080/Student
Content-Type: application/json

{
  "firstName": "student",
  "lastName": "4",
  "phoneNumber": "122423454"
}

### Delete Student by id
DELETE http://localhost:8080/Student/b66a0faf-3b4a-4422-b9d6-bf628337295a

### Update Student Data

Put http://localhost:8080/localhost:8080/Student
Content-Type: application/json

{
  "id": "f551423a-def5-42b6-b12c-363c4f55f37b",
  "firstName": "student",
  "lastName": "5",
  "phoneNumber": "90371223454"
}

##################################

### Enroll & Unenroll student in course

#  "/{studentId}/enroll/{courseId}"

### Enroll

POST http://localhost:8080/Student/b66a0faf-3b4a-4422-b9d6-bf628337295a/enroll/a827c784-84ff-4ff8-b407-d1a2d39b7323
###

POST http://localhost:8080/Student/enroll
Content-Type: application/json

{
  "studentId": "f551423a-def5-42b6-b12c-363c4f55f37b",
  "courseId": "9b60fc69-95e7-4060-aec7-b9ba566e9766",
  "role" : "Enrol"
}

### Unenroll 

POST http://localhost:8080/Student/f551423a-def5-42b6-b12c-363c4f55f37b/unenroll/8b961aa5-4ed3-446e-bc93-8a1a31eeab28
